index:
  path: /
  controller: App\Controller\PortadaController::index

#buscador:
#  path: /busqueda
#  controller: App\Controller\BuscadorController::index

buscador_mediciones:
  path: /busqueda/mediciones_fotos
  controller: App\Controller\BuscadorController::mediciones_fotos

buscador_datos:
  path: /busqueda/datos
  controller: App\Controller\BuscadorController::datos

buscador_detalles:
  path: /busqueda/detalles/{id}
  controller: App\Controller\BuscadorController::detalles

buscador_descargar:
  path: /busqueda/descargar/{id}
  controller: App\Controller\BuscadorController::descargarTodo

usuarios:
  path: /user
  controller: App\Controller\UserController::index

contacto:
  path: /contacto
  controller: App\Controller\ContactoController::index

mapa_qgis:
  path: /mapa
  controller: App\Controller\MapaQgisController::index
