index:
  path: /
  controller: App\Controller\PortadaController::index

#buscador:
#  path: /busqueda
#  controller: App\Controller\BuscadorController::index

buscador_mapas:
  path: /busqueda/mapas_fotos
  controller: App\Controller\BuscadorController::mapas_fotos

buscador_datos:
  path: /busqueda/datos
  controller: App\Controller\BuscadorController::datos

buscador_detalles:
  path: /busqueda/detalles/{id}
  controller: App\Controller\BuscadorController::detalles

usuarios:
  path: /user
  controller: App\Controller\UserController::index

contacto:
  path: /contacto
  controller: App\Controller\ContactoController::index
